package com.invoproj.beans.invoice;
// default package
// Generated Feb 3, 2017 1:26:39 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.codehaus.jackson.annotate.JsonProperty;

/**
 * PayableReceivable generated by hbm2java
 */
public class PayableReceivable implements java.io.Serializable {

	private String invoiceNo;
	private String payableReceivable;
	private String fromTo;
	private String invoiceType;
	private Boolean isSaveForLater;
	@JsonProperty
	private boolean isActive;
	private Date createdOn;
	private Date modifiedOn;
	private Set offers = new HashSet(0);
	private Set presentCollects = new HashSet(0);
	
	private Long idBatchInvoice;
	private Long idCreaditNote;
	private Long idNego;
	private Long idAlert;
	private Long idOffer;
	private Long idPayableReceivable;
	private Long idUserProfileFm;
	//private UserProfile userProfile;
	private List<Invoice> invoice;
	private File idFileCrNt;;

	public PayableReceivable() {
	}

	public PayableReceivable(File fileByIdFileInvo, String payableReceivable,
			boolean isActive, Date createdOn) {
		this.idFileInvo = fileByIdFileInvo;
		this.payableReceivable = payableReceivable;
		this.isActive = isActive;
		this.createdOn = createdOn;
	}

	public PayableReceivable(File fileByIdFileInvo, /*UserProfile userProfile,*/
			List<Invoice> invoice, File fileByIdFileCrNt, String invoiceNo,
			Long idBatchInvoice, String payableReceivable,
			Long idUserProfileFm, String fromTo, Long idCreaditNote,
			String invoiceType, Long idNego, Long idAlert, Long idOffer,
			Boolean isSaveForLater, boolean isActive, Date createdOn,
			Date modifiedOn, Set offers, Set presentCollects) {
		this.idFileInvo = fileByIdFileInvo;
		//this.userProfile = userProfile;
		this.invoice = invoice;
		this.idFileCrNt = fileByIdFileCrNt;
		this.invoiceNo = invoiceNo;
		this.idBatchInvoice = idBatchInvoice;
		this.payableReceivable = payableReceivable;
		this.idUserProfileFm = idUserProfileFm;
		this.fromTo = fromTo;
		this.idCreaditNote = idCreaditNote;
		this.invoiceType = invoiceType;
		this.idNego = idNego;
		this.idAlert = idAlert;
		this.idOffer = idOffer;
		this.isSaveForLater = isSaveForLater;
		this.isActive = isActive;
		this.createdOn = createdOn;
		this.modifiedOn = modifiedOn;
		this.offers = offers;
		this.presentCollects = presentCollects;
	}

	public Long getIdPayableReceivable() {
		return this.idPayableReceivable;
	}

	public void setIdPayableReceivable(Long idPayableReceivable) {
		this.idPayableReceivable = idPayableReceivable;
	}

	/*public UserProfile getUserProfile() {
		return this.userProfile;
	}

	public void setUserProfile(UserProfile userProfile) {
		this.userProfile = userProfile;
	}*/

	public List<Invoice> getInvoice() {
		return this.invoice;
	}

	public void setInvoice(List<Invoice> invoice) {
		this.invoice = invoice;
	}

	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	public Long getIdBatchInvoice() {
		return this.idBatchInvoice;
	}

	public void setIdBatchInvoice(Long idBatchInvoice) {
		this.idBatchInvoice = idBatchInvoice;
	}

	public String getPayableReceivable() {
		return this.payableReceivable;
	}

	public void setPayableReceivable(String payableReceivable) {
		this.payableReceivable = payableReceivable;
	}

	public Long getIdUserProfileFm() {
		return this.idUserProfileFm;
	}

	public void setIdUserProfileFm(Long idUserProfileFm) {
		this.idUserProfileFm = idUserProfileFm;
	}

	public String getFromTo() {
		return this.fromTo;
	}

	public void setFromTo(String fromTo) {
		this.fromTo = fromTo;
	}

	public Long getIdCreaditNote() {
		return this.idCreaditNote;
	}

	public void setIdCreaditNote(Long idCreaditNote) {
		this.idCreaditNote = idCreaditNote;
	}

	public String getInvoiceType() {
		return this.invoiceType;
	}

	public void setInvoiceType(String invoiceType) {
		this.invoiceType = invoiceType;
	}

	public Long getIdNego() {
		return this.idNego;
	}

	public void setIdNego(Long idNego) {
		this.idNego = idNego;
	}

	public Long getIdAlert() {
		return this.idAlert;
	}

	public void setIdAlert(Long idAlert) {
		this.idAlert = idAlert;
	}

	public Long getIdOffer() {
		return this.idOffer;
	}

	public void setIdOffer(Long idOffer) {
		this.idOffer = idOffer;
	}

	public Boolean getIsSaveForLater() {
		return this.isSaveForLater;
	}

	public void setIsSaveForLater(Boolean isSaveForLater) {
		this.isSaveForLater = isSaveForLater;
	}

	public boolean isIsActive() {
		return this.isActive;
	}

	public void setIsActive(boolean isActive) {
		this.isActive = isActive;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public Set getOffers() {
		return this.offers;
	}

	public void setOffers(Set offers) {
		this.offers = offers;
	}

	public Set getPresentCollects() {
		return this.presentCollects;
	}

	public void setPresentCollects(Set presentCollects) {
		this.presentCollects = presentCollects;
	}
	private File idFileInvo;
	public File getIdFileInvo() {
		return idFileInvo;
	}

	public void setIdFileInvo(File idFileInvo) {
		this.idFileInvo = idFileInvo;
	}

	public File getIdFileCrNt() {
		return idFileCrNt;
	}

	public void setIdFileCrNt(File idFileCrNt) {
		this.idFileCrNt = idFileCrNt;
	}

}
